/// x86-64 bootloader generator.
///
/// Generates a minimal x86-64 bootloader that:
///   • Runs in long mode (64-bit)
///   • Supports both legacy BIOS (via Multiboot2) and UEFI boot paths
///   • Sets up a flat GDT, a minimal IDT and a basic page table
///   • Hands off to the Dart kernel binary
library;

import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:logging/logging.dart';

// ─────────────────────────────────────────────────────────────────────────────
// X86BootMode
// ─────────────────────────────────────────────────────────────────────────────

/// x86 boot method.
enum X86BootMode {
  /// Legacy BIOS boot via Multiboot2 header (GRUB / QEMU).
  multiboot2,

  /// UEFI boot via a PE32+ application.
  uefi,
}

// ─────────────────────────────────────────────────────────────────────────────
// X86Bootloader
// ─────────────────────────────────────────────────────────────────────────────

/// Generates x86-64 bootloader Assembly source and linker scripts.
final class X86Bootloader {
  final X86BootMode bootMode;

  /// Physical address where the kernel image will be loaded.
  final int kernelLoadAddress;

  /// Size of the initial stack in bytes.
  final int stackSize;

  static final _log = Logger('X86Bootloader');

  X86Bootloader({
    this.bootMode          = X86BootMode.multiboot2,
    this.kernelLoadAddress = 0x100000, // 1 MB — classic Linux load address
    this.stackSize         = 0x10000,  // 64 KB
  });

  // ─── Assembly generation ───────────────────────────────────────────────────

  /// Generate the x86-64 startup Assembly source.
  String generateBootloaderAsm() => switch (bootMode) {
        X86BootMode.multiboot2 => _generateMultiboot2Asm(),
        X86BootMode.uefi       => _generateUefiStubAsm(),
      };

  String _generateMultiboot2Asm() => '''
/*
 * kernel_dart — x86-64 Multiboot2 Bootloader
 * Loaded by GRUB or QEMU -kernel flag.
 *
 * Boot sequence:
 *   1. GRUB verifies Multiboot2 header
 *   2. CPU is in 32-bit protected mode
 *   3. We switch to 64-bit long mode
 *   4. Set up GDT, IDT, page tables
 *   5. Jump to Dart kernel
 *
 * Auto-generated by kernel_dart X86Bootloader.
 */

/* ── Multiboot2 header (must be in first 32 KB of image) ─────────────────── */
.section ".multiboot", "a"
.align 8
multiboot2_header:
    .long   0xE85250D6          /* Multiboot2 magic                          */
    .long   0                   /* architecture: 0 = i386 (32-bit protected) */
    .long   .multiboot2_end - multiboot2_header   /* header length           */
    .long   -(0xE85250D6 + 0 + (.multiboot2_end - multiboot2_header)) /* checksum */
    /* End tag */
    .short  0                   /* type = end                                */
    .short  0                   /* flags                                     */
    .long   8                   /* size                                      */
.multiboot2_end:

/* ── 32-bit entry (Multiboot2 lands here) ────────────────────────────────── */
.section ".text32"
.code32
.global _start32
_start32:
    cli
    /* Save Multiboot2 info pointer (ebx) */
    mov     %ebx, %edi

    /* Load our 32-bit GDT */
    lgdt    (gdt32_ptr)

    /* Reload segments */
    ljmp    \$0x08, \$.reload_cs32
.reload_cs32:
    mov     \$0x10, %ax
    mov     %ax, %ds
    mov     %ax, %es
    mov     %ax, %ss
    mov     %ax, %fs
    mov     %ax, %gs

    /* Set up 32-bit stack */
    mov     \$boot_stack_top32, %esp

    /* Enable PAE */
    mov     %cr4, %eax
    or      \$0x20, %eax
    mov     %eax, %cr4

    /* Load PML4 table base into CR3 */
    mov     \$pml4_table, %eax
    mov     %eax, %cr3

    /* Build identity page tables (0 – 2 GB) */
    call    setup_page_tables

    /* Enable long mode (LME bit in EFER MSR) */
    mov     \$0xC0000080, %ecx
    rdmsr
    or      \$0x100, %eax
    wrmsr

    /* Enable paging + protected mode */
    mov     %cr0, %eax
    or      \$0x80000001, %eax
    mov     %eax, %cr0

    /* Long jump to 64-bit code segment */
    ljmp    \$0x18, \$._start64

/* ── 32-bit page table setup ─────────────────────────────────────────────── */
setup_page_tables:
    /* PML4[0] → PDPT */
    mov     \$pdpt_table, %eax
    or      \$0x03, %eax
    mov     %eax, pml4_table

    /* PDPT[0] → PD */
    mov     \$pd_table, %eax
    or      \$0x03, %eax
    mov     %eax, pdpt_table

    /* PD[0..511] → 2 MB huge pages (identity map first 1 GB) */
    xor     %ecx, %ecx
.pd_loop:
    mov     %ecx, %eax
    shl     \$21, %eax       /* 2 MB per entry */
    or      \$0x83, %eax     /* present | writable | huge */
    mov     %eax, pd_table(, %ecx, 8)
    inc     %ecx
    cmp     \$512, %ecx
    jl      .pd_loop
    ret

/* ── 64-bit code ─────────────────────────────────────────────────────────── */
.section ".text"
.code64
._start64:
    /* Reload 64-bit GDT */
    lgdt    (gdt64_ptr)

    /* Reload data segments with 64-bit selectors */
    xor     %rax, %rax
    mov     %ax, %ds
    mov     %ax, %es
    mov     %ax, %ss
    mov     %ax, %fs
    mov     %ax, %gs

    /* Set up 64-bit stack */
    mov     \$boot_stack_top64, %rsp

    /* Load IDT */
    lidt    (idt_ptr)

    /* Clear BSS */
    mov     \$__bss_start, %rdi
    mov     \$__bss_end,   %rcx
    sub     %rdi, %rcx
    xor     %rax, %rax
    shr     \$3, %rcx
    rep     stosq

    /* Enable SSE / SSE2 (Dart runtime needs them) */
    mov     %cr0, %rax
    and     \$0xFFFFFFFFFFFFFFFB, %rax   /* clear EM */
    or      \$0x2, %rax                   /* set MP  */
    mov     %rax, %cr0
    mov     %cr4, %rax
    or      \$0x600, %rax                 /* set OSFXSR + OSXMMEXCPT */
    mov     %rax, %cr4

    /* rdi already contains Multiboot2 info pointer from 32-bit stage */
    /* Call C boot init which builds BootInfo and calls dart_kernel_main */
    call    boot_init_x86

.hang64:
    hlt
    jmp     .hang64

/* ── GDT descriptors ─────────────────────────────────────────────────────── */
.section ".data"
.align 8
gdt32:
    .quad   0x0000000000000000    /* null descriptor */
    .quad   0x00CF9A000000FFFF    /* code32: base=0, limit=4G, ring0, r-x  */
    .quad   0x00CF92000000FFFF    /* data32: base=0, limit=4G, ring0, rw-  */
    .quad   0x00AF9A000000FFFF    /* code64: long-mode, ring0, r-x         */
gdt32_ptr:
    .short  . - gdt32 - 1
    .long   gdt32

gdt64:
    .quad   0x0000000000000000
    .quad   0x00AF9A000000FFFF    /* code64 */
    .quad   0x00AF92000000FFFF    /* data64 */
gdt64_ptr:
    .short  . - gdt64 - 1
    .quad   gdt64

/* ── Minimal IDT (256 entries, all pointing to default handler) ────────────── */
idt_table:
    .rept 256
    .quad 0
    .quad 0
    .endr
idt_ptr:
    .short  . - idt_table - 1
    .quad   idt_table

/* ── Page tables (4 KB aligned) ──────────────────────────────────────────── */
.section ".bss"
.align 4096
pml4_table: .space 4096
pdpt_table: .space 4096
pd_table:   .space 4096

/* ── Stacks ───────────────────────────────────────────────────────────────── */
.align 16
    .space 4096
boot_stack_top32:
    .space 65536
boot_stack_top64:

/* ── BSS markers (set by linker script) ──────────────────────────────────── */
__bss_start = .;
__bss_end   = . + 0x1000;
''';

  String _generateUefiStubAsm() => '''
/*
 * kernel_dart — UEFI Boot Stub (x86-64)
 *
 * This stub is compiled as a PE32+ EFI Application.
 * The UEFI firmware calls efi_main(EFI_HANDLE, EFI_SYSTEM_TABLE*).
 * We use Boot Services to allocate memory, load the kernel image,
 * exit Boot Services, and jump to the kernel.
 *
 * The actual C implementation is in uefi_loader.dart (Dart codegen).
 * This file provides only the PE32+ entry-point thunk.
 */

.section ".text"
.global _start
_start:
    /* UEFI calls _start(image_handle: RCX, system_table: RDX) on Windows ABI */
    /* Convert Windows ABI → System V AMD64 ABI for our C code */
    mov     %rcx, %rdi   /* image_handle → rdi */
    mov     %rdx, %rsi   /* system_table → rsi */
    call    efi_main
    ret
''';

  // ─── Linker script generation ──────────────────────────────────────────────

  /// Generate a GNU LD linker script for the chosen [bootMode].
  String generateLinkerScript() {
    final kernelHex = '0x${kernelLoadAddress.toRadixString(16)}';

    return switch (bootMode) {
      X86BootMode.multiboot2 => '''
/*
 * kernel_dart — x86-64 Multiboot2 Linker Script
 * Auto-generated by kernel_dart X86Bootloader.
 */

OUTPUT_FORMAT("elf64-x86-64")
OUTPUT_ARCH("i386:x86-64")
ENTRY(_start32)

SECTIONS
{
    . = $kernelHex;

    .multiboot : {
        KEEP(*(.multiboot))
    }

    .text32 : {
        KEEP(*(.text32))
    }

    .text : {
        *(.text*)
        *(.rodata*)
        . = ALIGN(4096);
    }

    .data : {
        *(.data*)
        *(.eh_frame*)
        . = ALIGN(4096);
    }

    __bss_start = .;
    .bss : {
        *(.bss*)
        *(COMMON)
        . = ALIGN(4096);
    }
    __bss_end = .;

    /DISCARD/ : {
        *(.comment)
        *(.note*)
        *(.gnu.version*)
    }
}
''',
      X86BootMode.uefi => '''
/*
 * kernel_dart — x86-64 UEFI PE32+ Linker Script
 * Auto-generated by kernel_dart X86Bootloader.
 */

OUTPUT_FORMAT("pei-x86-64")
ENTRY(_start)

SECTIONS
{
    . = 0;
    .text : { *(.text*) *(.rodata*) }
    .data : { *(.data*) }
    .bss  : { *(.bss*)  }
}
''',
    };
  }

  // ─── File output ──────────────────────────────────────────────────────────

  /// Write Assembly source and linker script to [outputDir].
  Future<void> writeFiles(String outputDir) async {
    Directory(outputDir).createSync(recursive: true);

    final suffix  = bootMode.name;
    final asmFile = File(p.join(outputDir, 'startup_x86_$suffix.S'));
    final ldFile  = File(p.join(outputDir, 'linker_x86_$suffix.ld'));

    asmFile.writeAsStringSync(generateBootloaderAsm());
    ldFile.writeAsStringSync(generateLinkerScript());

    _log.info('x86 bootloader files written to $outputDir');
    _log.info('  ${asmFile.path}');
    _log.info('  ${ldFile.path}');
  }
}
