/// ARM / ARM64 bootloader generator.
///
/// Generates architecture-specific bootloader Assembly and linker scripts
/// that set up the CPU environment and hand off to the Dart kernel binary.
///
/// Supports:
///   • ARMv7-A (Cortex-A7, A17, A53 in 32-bit mode)
///   • AArch64 (Cortex-A53, A72, A76 — Raspberry Pi 3/4/5)
library;

import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:logging/logging.dart';

import 'boot_protocol.dart';

// ─────────────────────────────────────────────────────────────────────────────
// TargetBoard — known ARM boards
// ─────────────────────────────────────────────────────────────────────────────

/// A known ARM board and its hardware parameters.
enum TargetBoard {
  raspberryPi3(
    name:        'Raspberry Pi 3',
    cpuModel:    'Cortex-A53',
    ramBase:     0x00000000,
    ramSize:     0x40000000,  // 1 GB
    uartBase:    0x3F201000,
    gpioBase:    0x3F200000,
    timerBase:   0x3F003000,
    gicBase:     0x3F00B000,
    stackTop:    0x00040000,
    kernelLoad:  0x00080000,
  ),
  raspberryPi4(
    name:        'Raspberry Pi 4',
    cpuModel:    'Cortex-A72',
    ramBase:     0x00000000,
    ramSize:     0x100000000, // 4 GB
    uartBase:    0xFE201000,
    gpioBase:    0xFE200000,
    timerBase:   0xFE003000,
    gicBase:     0xFF841000,
    stackTop:    0x00080000,
    kernelLoad:  0x00080000,
  ),
  genericArm64(
    name:        'Generic ARM64',
    cpuModel:    'Cortex-A',
    ramBase:     0x40000000,
    ramSize:     0x40000000,  // 1 GB
    uartBase:    0x09000000,
    gpioBase:    0x09010000,
    timerBase:   0x09020000,
    gicBase:     0x08000000,
    stackTop:    0x40080000,
    kernelLoad:  0x40080000,
  ),
  genericArm32(
    name:        'Generic ARM32',
    cpuModel:    'Cortex-A7',
    ramBase:     0x80000000,
    ramSize:     0x20000000,  // 512 MB
    uartBase:    0x01C28000,
    gpioBase:    0x01C20800,
    timerBase:   0x01C20C00,
    gicBase:     0x01C80000,
    stackTop:    0x80040000,
    kernelLoad:  0x80080000,
  );

  final String name;
  final String cpuModel;
  final int ramBase;
  final int ramSize;
  final int uartBase;
  final int gpioBase;
  final int timerBase;
  final int gicBase;
  final int stackTop;
  final int kernelLoad;

  const TargetBoard({
    required this.name,
    required this.cpuModel,
    required this.ramBase,
    required this.ramSize,
    required this.uartBase,
    required this.gpioBase,
    required this.timerBase,
    required this.gicBase,
    required this.stackTop,
    required this.kernelLoad,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// ARMBootloader
// ─────────────────────────────────────────────────────────────────────────────

/// Generates ARM64 (AArch64) bootloader Assembly source.
///
/// The generated code:
///   1. Masks all IRQs and FIQs
///   2. Sets up the initial stack pointer
///   3. Clears the BSS segment (zero-initialises global variables)
///   4. Initialises UART for early debug output
///   5. Initialises the Generic Interrupt Controller (GIC)
///   6. Builds a [BootInfo] structure in RAM
///   7. Jumps to the Dart kernel entry point
final class ARMBootloader {
  final TargetBoard targetBoard;

  /// Physical address at which the bootloader is loaded by firmware.
  final int memoryBaseAddress;

  /// Physical address where the Dart kernel binary is expected.
  final int kernelLoadAddress;

  /// AArch64 mode (true) or ARMv7-A 32-bit mode (false).
  final bool aarch64;

  static final _log = Logger('ARMBootloader');

  ARMBootloader({
    required this.targetBoard,
    int? memoryBaseAddress,
    int? kernelLoadAddress,
    this.aarch64 = true,
  })  : memoryBaseAddress = memoryBaseAddress ?? targetBoard.stackTop,
        kernelLoadAddress = kernelLoadAddress ?? targetBoard.kernelLoad;

  // ─── Assembly generation ───────────────────────────────────────────────────

  /// Generate the AArch64 startup Assembly source (.S file contents).
  String generateBootloaderAsm() => aarch64
      ? _generateAarch64Asm()
      : _generateArm32Asm();

  String _generateAarch64Asm() {
    final kernelHex = '0x${kernelLoadAddress.toRadixString(16)}';
    final uartHex   = '0x${targetBoard.uartBase.toRadixString(16)}';

    return '''
/*
 * kernel_dart — AArch64 Bootloader Startup
 * Target: ${targetBoard.name} (${targetBoard.cpuModel})
 *
 * Register conventions on entry (from firmware):
 *   x0 = FDT blob pointer (or 0)
 *   x1 = x2 = x3 = 0
 *   x4 = kernel entry address (from ATF/UEFI)
 *
 * Auto-generated by kernel_dart ARMBootloader.
 * DO NOT EDIT — regenerate via kernel_dart build.
 */

.section ".boot", "ax"
.global _start

_start:
    /* ── Mask all exceptions (DAIF bits) ──────────────────────────────────── */
    msr     DAIFSet, #0xF

    /* ── CPU 0 only: all other CPUs spin in a WFE loop ───────────────────── */
    mrs     x0, mpidr_el1
    and     x0, x0, #0xFF
    cbz     x0, .cpu0_init
.secondary_spin:
    wfe
    b       .secondary_spin

.cpu0_init:
    /* ── Set up initial stack ─────────────────────────────────────────────── */
    ldr     x0, =boot_stack_top
    mov     sp, x0

    /* ── Enable FP/SIMD (needed by Dart runtime) ──────────────────────────── */
    mov     x0, #(3 << 20)
    msr     cpacr_el1, x0
    isb

    /* ── Set up EL1 vector table ──────────────────────────────────────────── */
    ldr     x0, =exception_vector_table
    msr     vbar_el1, x0
    isb

    /* ── Clear BSS ────────────────────────────────────────────────────────── */
    ldr     x0, =__bss_start
    ldr     x1, =__bss_end
    cmp     x0, x1
    b.ge    .bss_done
.bss_loop:
    str     xzr, [x0], #8
    cmp     x0, x1
    b.lt    .bss_loop
.bss_done:

    /* ── Copy .data section from ROM/flash to RAM ─────────────────────────── */
    ldr     x0, =__data_load_start    /* source (ROM/flash) */
    ldr     x1, =__data_start         /* destination (RAM)  */
    ldr     x2, =__data_end
    cmp     x1, x2
    b.ge    .data_done
.data_loop:
    ldr     x3, [x0], #8
    str     x3, [x1], #8
    cmp     x1, x2
    b.lt    .data_loop
.data_done:

    /* ── Initialise UART for early debug output ───────────────────────────── */
    ldr     x0, =$uartHex
    bl      uart_early_init

    /* ── Print boot banner ────────────────────────────────────────────────── */
    adr     x0, .boot_banner
    bl      uart_print_str

    /* ── Initialise GIC (Generic Interrupt Controller) ────────────────────── */
    ldr     x0, =0x${targetBoard.gicBase.toRadixString(16)}
    bl      gic_init

    /* ── Enable IRQ at EL1 (keep FIQ masked) ─────────────────────────────── */
    msr     DAIFClr, #0x2

    /* ── Jump to Dart kernel entry point ─────────────────────────────────── */
    /* x0 = pointer to boot_info structure (built in BSS) */
    ldr     x0, =_boot_info
    ldr     x1, =$kernelHex
    br      x1

    /* Should never reach here */
.hang:
    wfe
    b       .hang

/* ── Boot banner string ───────────────────────────────────────────────────── */
.boot_banner:
    .asciz  "kernel_dart ${targetBoard.name} booting...\\r\\n"

/* ── Boot stack (4 KB, 16-byte aligned for AArch64 ABI) ───────────────────── */
.section ".bss"
.align 4
    .space 4096
boot_stack_top:

/* ── BootInfo placeholder (filled in by C code) ──────────────────────────── */
_boot_info:
    .space  256
''';
  }

  String _generateArm32Asm() {
    final stackHex  = '0x${memoryBaseAddress.toRadixString(16)}';
    final kernelHex = '0x${kernelLoadAddress.toRadixString(16)}';

    return '''
/*
 * kernel_dart — ARMv7-A (32-bit) Bootloader Startup
 * Target: ${targetBoard.name} (${targetBoard.cpuModel})
 * Auto-generated by kernel_dart ARMBootloader.
 */

.section ".boot", "ax"
.global _start
.arm

_start:
    /* ── Disable IRQ & FIQ ────────────────────────────────────────────────── */
    cpsid   if

    /* ── Switch to SVC mode ───────────────────────────────────────────────── */
    mov     r0, #0xD3
    msr     cpsr_c, r0

    /* ── Set up stack ─────────────────────────────────────────────────────── */
    ldr     sp, =$stackHex

    /* ── Clear BSS ────────────────────────────────────────────────────────── */
    ldr     r0, =__bss_start
    ldr     r1, =__bss_end
    mov     r2, #0
.bss_loop:
    cmp     r0, r1
    strlt   r2, [r0], #4
    blt     .bss_loop

    /* ── Initialise UART ──────────────────────────────────────────────────── */
    ldr     r0, =0x${targetBoard.uartBase.toRadixString(16)}
    bl      uart_early_init

    /* ── Init interrupt controller ────────────────────────────────────────── */
    bl      gic_init

    /* ── Enable IRQs ──────────────────────────────────────────────────────── */
    cpsie   i

    /* ── Jump to Dart kernel ──────────────────────────────────────────────── */
    ldr     r0, =_boot_info
    ldr     r1, =$kernelHex
    bx      r1

.hang:
    wfi
    b       .hang

.section ".bss"
.align 2
    .space 4096
boot_stack_top:
_boot_info:
    .space 256
''';
  }

  // ─── Linker script generation ──────────────────────────────────────────────

  /// Generate a GNU LD linker script for this target.
  String generateLinkerScript() {
    final ramOrigin = '0x${targetBoard.ramBase.toRadixString(16)}';
    final ramLength = '${targetBoard.ramSize >> 20}M';
    final bootBase  = '0x${kernelLoadAddress.toRadixString(16)}';

    return '''
/*
 * kernel_dart Linker Script — ${targetBoard.name}
 * Auto-generated by kernel_dart ARMBootloader.
 */

OUTPUT_FORMAT("elf64-littleaarch64")
OUTPUT_ARCH(aarch64)

MEMORY
{
    /* Main RAM */
    RAM  (xrw) : ORIGIN = $ramOrigin, LENGTH = $ramLength
}

ENTRY(_start)

SECTIONS
{
    . = $bootBase;

    /* Boot code must be first */
    .boot : {
        KEEP(*(.boot))
        KEEP(*(.boot*))
    } > RAM

    /* Executable code */
    .text : {
        *(.text._start)
        *(.text*)
        *(.rodata*)
        . = ALIGN(4096);
    } > RAM

    /* Initialised data — loaded from ROM, copied to RAM */
    __data_load_start = LOADADDR(.data);
    .data : {
        __data_start = .;
        *(.data*)
        . = ALIGN(8);
        __data_end = .;
    } > RAM

    /* Exception vectors (must be 2KB-aligned on AArch64) */
    . = ALIGN(2048);
    .vectors : {
        KEEP(*(.vectors))
        exception_vector_table = .;
    } > RAM

    /* BSS — zero-initialised at startup */
    .bss : {
        . = ALIGN(8);
        __bss_start = .;
        *(.bss*)
        *(COMMON)
        . = ALIGN(8);
        __bss_end = .;
    } > RAM

    /* Dart heap starts immediately after BSS */
    __heap_start = __bss_end;
    __heap_end   = ORIGIN(RAM) + LENGTH(RAM) - 0x10000; /* leave 64 KB for IRQ stack */

    /* Discard unwanted sections */
    /DISCARD/ : {
        *(.comment)
        *(.note*)
        *(.ARM.exidx*)
        *(.gnu.version*)
    }
}
''';
  }

  // ─── File output ──────────────────────────────────────────────────────────

  /// Write both the Assembly source and linker script to [outputDir].
  Future<void> writeFiles(String outputDir) async {
    Directory(outputDir).createSync(recursive: true);

    final suffix = aarch64 ? 'arm64' : 'arm';
    final asmFile = File(p.join(outputDir, 'startup_$suffix.S'));
    final ldFile  = File(p.join(outputDir, 'linker_$suffix.ld'));

    asmFile.writeAsStringSync(generateBootloaderAsm());
    ldFile.writeAsStringSync(generateLinkerScript());

    _log.info('Bootloader files written to $outputDir');
    _log.info('  ${asmFile.path}');
    _log.info('  ${ldFile.path}');
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// BootloaderBuilder — orchestrates build + link
// ─────────────────────────────────────────────────────────────────────────────

/// Compiles and links the ARM bootloader using the cross-toolchain.
final class ARMBootloaderBuilder {
  final TargetBoard board;
  final String workDir;

  static final _log = Logger('ARMBootloaderBuilder');

  ARMBootloaderBuilder({required this.board, required this.workDir});

  Future<String> build({bool aarch64 = true}) async {
    final loader = ARMBootloader(targetBoard: board, aarch64: aarch64);
    await loader.writeFiles(workDir);

    final suffix  = aarch64 ? 'arm64' : 'arm';
    final asmPath = p.join(workDir, 'startup_$suffix.S');
    final ldPath  = p.join(workDir, 'linker_$suffix.ld');
    final objPath = p.join(workDir, 'startup_$suffix.o');
    final elfPath = p.join(workDir, 'bootloader_$suffix.elf');
    final binPath = p.join(workDir, 'bootloader_$suffix.bin');

    final prefix = aarch64 ? 'aarch64-linux-gnu-' : 'arm-linux-gnueabihf-';

    // Assemble
    await _run('${prefix}as', ['-o', objPath, asmPath], 'assemble bootloader');

    // Link
    await _run('${prefix}ld', ['-T', ldPath, '-o', elfPath, objPath], 'link bootloader');

    // Convert to raw binary
    await _run('${prefix}objcopy', ['-O', 'binary', elfPath, binPath], 'objcopy');

    _log.info('Bootloader built: $binPath (${File(binPath).lengthSync()} bytes)');
    return binPath;
  }

  Future<void> _run(String exe, List<String> args, String step) async {
    final r = await Process.run(exe, args);
    if (r.exitCode != 0) {
      throw ProcessException(exe, args, '$step failed: ${r.stderr}', r.exitCode);
    }
  }
}
