/// UEFI bootloader generator.
///
/// Generates a C source file that implements an EFI Application
/// (`efi_main`) using the UEFI Boot Services API to:
///   1. Locate the kernel image on the ESP (EFI System Partition)
///   2. Allocate a contiguous pool of physical memory
///   3. Load and decompress the kernel binary
///   4. Build the [BootInfo] hand-off structure
///   5. Exit Boot Services
///   6. Jump to the kernel entry point
///
/// The output is a `.c` file to be compiled with a UEFI-capable GCC
/// toolchain (gnu-efi or EDK2 headers).
library;

import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:logging/logging.dart';

// ─────────────────────────────────────────────────────────────────────────────
// UefiLoaderConfig
// ─────────────────────────────────────────────────────────────────────────────

/// Configuration for the generated UEFI loader.
final class UefiLoaderConfig {
  /// Filename of the kernel image on the ESP (e.g. `kernel.bin`).
  final String kernelFilename;

  /// Physical address to load the kernel at.
  final int kernelLoadAddress;

  /// Stack size allocated for the kernel (bytes).
  final int kernelStackSize;

  /// Maximum kernel image size (bytes) — used to pre-allocate memory.
  final int maxKernelSize;

  /// Print verbose boot messages via UEFI ConOut.
  final bool verbose;

  const UefiLoaderConfig({
    this.kernelFilename    = 'KERNEL.BIN',
    this.kernelLoadAddress = 0x100000,      // 1 MB
    this.kernelStackSize   = 0x10000,       // 64 KB
    this.maxKernelSize     = 0x400000,      // 4 MB
    this.verbose           = true,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// UefiLoader — C code generator
// ─────────────────────────────────────────────────────────────────────────────

/// Generates the UEFI EFI Application C source.
final class UefiLoader {
  final UefiLoaderConfig config;

  static final _log = Logger('UefiLoader');

  const UefiLoader({this.config = const UefiLoaderConfig()});

  // ─── C source generation ──────────────────────────────────────────────────

  /// Generate the complete UEFI loader C source.
  String generateCSource() {
    final kernelHex     = '0x${config.kernelLoadAddress.toRadixString(16)}';
    final stackSizeHex  = '0x${config.kernelStackSize.toRadixString(16)}';
    final maxKernelHex  = '0x${config.maxKernelSize.toRadixString(16)}';
    final kernelFile    = config.kernelFilename;

    return r'''
/*
 * kernel_dart — UEFI Loader
 *
 * Compiled as an EFI Application (PE32+ binary).
 * Loaded by UEFI firmware from EFI\BOOT\BOOTX64.EFI on the ESP.
 *
 * Build with:
 *   x86_64-w64-mingw32-gcc -o BOOTX64.EFI             \
 *       -nostdlib -fno-builtin -mno-red-zone            \
 *       -Wl,--subsystem,10 -Wl,-e,_start               \
 *       uefi_loader.c gnu-efi/lib/crt0-efi-x86_64.o    \
 *       -lgnu-efi -lgnu-efi-x86_64
 *
 * Auto-generated by kernel_dart UefiLoader.
 */

#include <efi.h>
#include <efilib.h>

''' +
        '/* ─────── Configuration ─────────────────────────────────────────── */\n'
        '#define KERNEL_FILENAME  L"$kernelFile"\n'
        '#define KERNEL_LOAD_ADDR $kernelHex\n'
        '#define KERNEL_STACK_SZ  $stackSizeHex\n'
        '#define MAX_KERNEL_SIZE  $maxKernelHex\n\n' +
        r'''
/* ─────── Boot Info structure (must match boot_protocol.dart) ─────────────── */
#define BOOT_INFO_MAGIC 0xB007DA37U

typedef struct {
    UINT32  magic;
    UINT32  version;
    UINT32  mmap_count;
    UINT32  uart_base;
    UINT32  cpu_clock_hz;
    UINT64  total_ram_bytes;
    UINT8   reserved[24];   /* pad to 64 bytes */
} BootInfoHeader;

typedef struct {
    UINT32  type;
    UINT64  physical_start;
    UINT64  size_bytes;
    UINT32  virtually_mapped;
} MemoryDescriptor;

/* ─────── Kernel entry point typedef ──────────────────────────────────────── */
typedef VOID (*KernelEntry)(BootInfoHeader *boot_info);

/* ─────── Helper: print string to console ─────────────────────────────────── */
static VOID
print(CHAR16 *msg)
{
    uefi_call_wrapper(ST->ConOut->OutputString, 2, ST->ConOut, msg);
}

/* ─────── Main UEFI entry point ───────────────────────────────────────────── */
EFI_STATUS
EFIAPI
efi_main(EFI_HANDLE image_handle, EFI_SYSTEM_TABLE *system_table)
{
    EFI_STATUS              status;
    EFI_LOADED_IMAGE       *loaded_image;
    EFI_SIMPLE_FILE_SYSTEM *fs;
    EFI_FILE_HANDLE         root, kernel_file;
    UINTN                   kernel_size;
    VOID                   *kernel_buffer;
    EFI_MEMORY_DESCRIPTOR  *mmap;
    UINTN                   mmap_size, mmap_key, desc_size;
    UINT32                  desc_version;
    BootInfoHeader         *boot_info;
    KernelEntry             entry;

    /* Initialise gnu-efi helper library */
    InitializeLib(image_handle, system_table);

    print(L"\r\nkernel_dart UEFI Loader v1.0\r\n");
    print(L"Loading kernel image: " KERNEL_FILENAME L"\r\n");

    /* ── Open the file system on the boot partition ──────────────────────── */
    status = uefi_call_wrapper(
        BS->HandleProtocol, 3,
        image_handle,
        &LoadedImageProtocol,
        (VOID **)&loaded_image
    );
    if (EFI_ERROR(status)) {
        print(L"ERROR: HandleProtocol(LoadedImage) failed\r\n");
        return status;
    }

    status = uefi_call_wrapper(
        BS->HandleProtocol, 3,
        loaded_image->DeviceHandle,
        &FileSystemProtocol,
        (VOID **)&fs
    );
    if (EFI_ERROR(status)) {
        print(L"ERROR: HandleProtocol(FileSystem) failed\r\n");
        return status;
    }

    status = uefi_call_wrapper(fs->OpenVolume, 2, fs, &root);
    if (EFI_ERROR(status)) {
        print(L"ERROR: OpenVolume failed\r\n");
        return status;
    }

    /* ── Open kernel image file ───────────────────────────────────────────── */
    status = uefi_call_wrapper(
        root->Open, 5,
        root,
        &kernel_file,
        KERNEL_FILENAME,
        EFI_FILE_MODE_READ,
        0
    );
    if (EFI_ERROR(status)) {
        print(L"ERROR: Kernel file not found: " KERNEL_FILENAME L"\r\n");
        return status;
    }

    /* ── Allocate memory for kernel image ────────────────────────────────── */
    kernel_size   = MAX_KERNEL_SIZE;
    kernel_buffer = (VOID *)KERNEL_LOAD_ADDR;

    status = uefi_call_wrapper(
        BS->AllocatePages, 4,
        AllocateAddress,
        EfiLoaderData,
        EFI_SIZE_TO_PAGES(kernel_size),
        (EFI_PHYSICAL_ADDRESS *)&kernel_buffer
    );
    if (EFI_ERROR(status)) {
        print(L"ERROR: AllocatePages for kernel failed\r\n");
        return status;
    }

    /* ── Read kernel image ───────────────────────────────────────────────── */
    status = uefi_call_wrapper(kernel_file->Read, 3, kernel_file, &kernel_size, kernel_buffer);
    uefi_call_wrapper(kernel_file->Close, 1, kernel_file);

    if (EFI_ERROR(status)) {
        print(L"ERROR: Kernel file read failed\r\n");
        return status;
    }

    print(L"Kernel loaded. Getting memory map...\r\n");

    /* ── Get UEFI memory map ─────────────────────────────────────────────── */
    mmap_size = 0;
    status    = uefi_call_wrapper(
        BS->GetMemoryMap, 5,
        &mmap_size, NULL, &mmap_key, &desc_size, &desc_version
    );
    mmap_size += 2 * desc_size; /* add room for new entries */

    status = uefi_call_wrapper(BS->AllocatePool, 3, EfiLoaderData, mmap_size, (VOID **)&mmap);
    status = uefi_call_wrapper(
        BS->GetMemoryMap, 5,
        &mmap_size, mmap, &mmap_key, &desc_size, &desc_version
    );
    if (EFI_ERROR(status)) {
        print(L"ERROR: GetMemoryMap failed\r\n");
        return status;
    }

    /* ── Build BootInfo ──────────────────────────────────────────────────── */
    status = uefi_call_wrapper(
        BS->AllocatePool, 3, EfiLoaderData, sizeof(BootInfoHeader), (VOID **)&boot_info
    );
    boot_info->magic          = BOOT_INFO_MAGIC;
    boot_info->version        = 1;
    boot_info->mmap_count     = (UINT32)(mmap_size / desc_size);
    boot_info->uart_base      = 0x000003F8;   /* COM1 on x86 */
    boot_info->cpu_clock_hz   = 2000000000U;  /* 2 GHz default */
    boot_info->total_ram_bytes = 0;           /* computed from mmap */

    /* Sum usable RAM */
    EFI_MEMORY_DESCRIPTOR *d = mmap;
    for (UINTN i = 0; i < boot_info->mmap_count; i++) {
        if (d->Type == EfiConventionalMemory) {
            boot_info->total_ram_bytes += d->NumberOfPages * EFI_PAGE_SIZE;
        }
        d = (EFI_MEMORY_DESCRIPTOR *)((UINT8 *)d + desc_size);
    }

    /* ── Exit Boot Services ──────────────────────────────────────────────── */
    status = uefi_call_wrapper(BS->ExitBootServices, 2, image_handle, mmap_key);
    if (EFI_ERROR(status)) {
        /* One retry after re-fetching the map is standard practice */
        mmap_size = 0;
        uefi_call_wrapper(
            BS->GetMemoryMap, 5,
            &mmap_size, mmap, &mmap_key, &desc_size, &desc_version
        );
        status = uefi_call_wrapper(BS->ExitBootServices, 2, image_handle, mmap_key);
        if (EFI_ERROR(status)) {
            /* Can't print after failed ExitBootServices — just hang */
            for (;;) __asm__("hlt");
        }
    }

    /* ── Jump to Dart kernel ─────────────────────────────────────────────── */
    entry = (KernelEntry)KERNEL_LOAD_ADDR;
    entry(boot_info);

    /* Never reached */
    for (;;) __asm__("hlt");
    return EFI_SUCCESS;
}
''';
  }

  // ─── Makefile generation ──────────────────────────────────────────────────

  /// Generate a Makefile for building the UEFI loader.
  String generateMakefile() => r'''
# kernel_dart — UEFI Loader Makefile
# Requires: gnu-efi, x86_64-w64-mingw32-gcc or clang with UEFI target

CC      := x86_64-w64-mingw32-gcc
CFLAGS  := -nostdlib -fno-builtin -mno-red-zone -Wall -Wextra \
           -I/usr/include/efi -I/usr/include/efi/x86_64 \
           -DEFI_FUNCTION_WRAPPER
LDFLAGS := -Wl,--subsystem,10 -Wl,-e,_start \
           -Wl,-Map=BOOTX64.map
LIBS    := -lgnu-efi -lgnu-efi-x86_64
GNUEFI  := /usr/lib/gnuefi/x86_64/crt0-efi-x86_64.o

OUTDIR  := build/uefi
TARGET  := $(OUTDIR)/BOOTX64.EFI

.PHONY: all clean

all: $(TARGET)

$(OUTDIR):
	mkdir -p $@

$(TARGET): uefi_loader.c | $(OUTDIR)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(GNUEFI) $< $(LIBS)

clean:
	rm -rf $(OUTDIR)
''';

  // ─── File output ──────────────────────────────────────────────────────────

  /// Write the generated C source and Makefile to [outputDir].
  Future<void> writeFiles(String outputDir) async {
    Directory(outputDir).createSync(recursive: true);

    final cFile   = File(p.join(outputDir, 'uefi_loader.c'));
    final mkFile  = File(p.join(outputDir, 'Makefile.uefi'));

    cFile.writeAsStringSync(generateCSource());
    mkFile.writeAsStringSync(generateMakefile());

    _log.info('UEFI loader files written to $outputDir');
    _log.info('  ${cFile.path}');
    _log.info('  ${mkFile.path}');
  }
}
